---
- hosts: 172.31.24.41
  become: yes
  tasks: 
   - name: install git
     apt:
      name: git
      state: present

   - name: install tree
     apt:
      name: tree
      staaSte: present
     ignore_errors: yes

   - name: install wget
     apt:
      name: wget
      state : present