--- 
- hosts: 172.31.24.41
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webservers
    apt:
     name: apache2
     state: present
  - name: i want restart my webserver
    service:
     name: apache2
     state: restarted

  - name: i want to replace file on node side
    template:
     src: myindex.j2
     dest: /var/www/html/index.html