---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver on ubuntu node only
    apt:
     name: apache2
     state: present
<<<<<<< HEAD

    when: ansible_os_family== "Debian"

 
=======
     when: ansible_os_family== 'Debian'
  - name: i want to install webserver on redhat node only
    apt:
     name: httpd
     state: present
     when: ansible_os_family== 'redhat'
>>>>>>> 7851ff807de1b1555a8fe6aa54629d31f2a9625a
